transmission_regex = r'мкпп|механика|робот|вариатор|акпп|автомат'
odometer_regex = r'\d+\s?(?:\d{3}\s)?км'
fuel_regex = r'бензин|дизель|электро|гибрид|гбо'
horse_power_regex = r'(\d+)\s*л\.с\.'
engine_regex = r'\b\d+\.\d+\s*л?\b'

dict_param_separate = {
    'avito': '_',
    'drom': '_',
    'sberauto': '-'
}

dict_models = {
    '1 серии': r'1[- ]?(Series|серии|серия)',
    '2 серии': r'2[- ]?(Series|серии|серия)',
    '3 серии': r'3[- ]?(Series|серии|серия)',
    '4 серии': r'4[- ]?(Series|серии|серия)',
    '5 серии': r'5[- ]?(Series|серии|серия)',
    '6 серии': r'6[- ]?(Series|серии|серия)',
    '7 серии': r'7[- ]?(Series|серии|серия)',
    '8 серии': r'8[- ]?(Series|серии|серия)',
    'A-класс': r'A-(class|класс|klasse)?',
    'B-класс': r'B-(class|класс|klasse)?',
    'C-класс': r'C-(class|класс|klasse)?',
    'E-класс': r'E-(class|класс|klasse)?',
    'G-класс': r'G-(class|класс|klasse)?',
    'M-класс': r'M-(class|класс|klasse)?',
    'S-класс': r'S-(class|класс|klasse)?',
    'V-класс': r'V-(class|класс|klasse)?',
    'GL-класс': r'GL-(class|класс|klasse)?',
    'CLS-класс': r'CLS(-class|-класс|-klasse)?',
    'CLA-класс': r'CLA(-class|-класс|-klasse)?',
    'GLA-класс': r'GLA(-class|-класс|-klasse)?',
    'GLK-класс': r'GLK(-class|-класс|-klasse)?',
    'GLS-класс': r'GLS(-class|-класс|-klasse)?',
    'GLC-класс': r'GLC(-class|-класс|-klasse)?',
    'GLE-класс': r'GLE(-class|-класс|-klasse)?',
}


brand_models = {
    "acura": r"Guilia Quadrifoglio|TLX|RDX|MDX|ILX|NSX|TL|TSX|ZDX|RLX",
    "alfa romeo": r"Giulia Quadrifoglio|Giulia|Stelvio|Giulietta|Spider|Brera|4C|MiTo|159",
    "aston martin": r"V12 Vantage|V8 Vantage|Vanquish|Valkyrie|Valhalla|Virage|Rapide|Zagato|One-77|Cygnet|DB11|DBX|DBS|DB9",
    "audi": r"e-tron|RS[3456]|SQ[57]|A[3-8]|Q[3578]|TT|R8",
    "bentley": r"Continental|Bentayga|Flying Spur|Mulsanne|Arnage|Azure|Brooklands|Turbo R",
    "bmw": r"2[- ]?(Series|серии|серия)|4[- ]?(Series|серии|серия)|8[- ]?(Series|серии|серия)|3[- ]?(Series|серии|серия)|5[- ]?(Series|серии|серия)|7[- ]?(Series|серии|серия)|X5|X3|Z4|X4|M4|M5|X6|X7|X1|1[- ]?(Series|серии)|6[- ]?(Series|серии|серия)|X2|X6|i3|i8|XM|X4 M|X5 M|X6 M|M2|M3|M8|iX|iX3|i4|i7|2 Series Gran Coupe|4 Series Gran Coupe|8 Series Gran Coupe|X3 M|X4 M Competition|M240i|M340i|M550i|Z4 M40i|X7 M60i|i4 M50|iX M60|X5 M Competition|X6 M Competition",
    "brilliance": r"V5|H230|H330|H320|M2|V3|M1|H530|H220",
    "buick": r"Envision|Enclave|Encore|Regal|LaCrosse|Verano|Cascada|Excelle",
    "byd": r"Frigate 07|Destroyer 05|Corvette 07|Cruiser|Dolphin|Seal|Yuan|Song|Tang|Han|Qin|F[0367]|S[678]|E[123]|M6|D1|L3|G[36]|e[356]",
    "cadillac": r"Escalade|Eldorado|DeVille|XT[456]|CT6|ATS|CTS",
    "changan": r"Alsvin|CS35|CS55|UNI-T|UNI-K",
    "chery": r"Tiggo 7 Pro Max|Tiggo 4 Pro|Tiggo 8 Pro|Tiggo 7 Pro|Tiggo 7 Max|Exeed TXL|Crosseastar|Arrizo [3-8]|Tiggo [2-8]|Indis|Bonus",
    "chevrolet": r"Malibu Hybrid|Bolt EUV|Silverado|Trailblazer|Suburban|Corvette|Colorado|Traverse|Equinox|Captiva|Camaro|Tahoe|Malibu(?!Hybrid)|Impala|Tracker|Cruze|Bolt(?!EUV)|Trax|Spark|Onix|Niva|Aveo",
    "chrysler": r"Town & Country|PT Cruiser|Pacifica|Voyager|Sebring|Aspen|300|200",
    "citroen": r"C-Elysée|Berlingo|C[1-8]|Ami",
    "dacia": r"Bigster|Jogger|Spring|Dokker|Lodgy|Logan|Sandero|Duster",
    "daewoo": r"Nexia|Matiz|Gentra|Lacetti|Magnus|Lanos|Leganza|Nubira",
    "daihatsu": r"Terios|Sirion|Charade|Cuore|Mira|Rocky|Copen|Cast|Tanto",
    "datsun": r"mi-Do",
    "dodge": r"Challenger|Charger|Durango|Journey|Dart|Ram|Viper|Grand Caravan",
    "dongfeng": r"S30|AX7|H30|Rich|580|Glory 580|Aeolus|Fengguang",
    "ds": r"DS 3|DS 4|DS 5|DS 7 Crossback|DS 9|DS 6",
    "fiat": r"Punto|500|Ducato|Doblo|Tipo|Panda|Cronos|Argo|Mobi",
    "ford": r"Focus|Fiesta|Kuga|Mondeo|Explorer|F-150|Mustang|Escape|Expedition|Ranger|Bronco|Maverick|Fusion|Transit|Ecosport|Taurus|Edge|Flex|Expedition MAX|Super Duty|Raptor|Shelby GT500|Mustang Mach-E|F-150 Lightning|Bronco Sport|Ranger Raptor|Explorer ST|Expedition Platinum",
    "gac": r"gs8",
    "gaz": r"Gazelle|Sobol|Valday|Sadko|Siber|GAZelle NEXT|GAZelle NN|Sobol NN|Siber NN",
    "geely": r"Atlas|Coolray|Emgrand|Tugella|Azkarra|Borui|Geometry A|Preface|Vision X6|Monjaro|Okavango|Belgee|Boyue|Geometry(?:A|C|E)|Preface",
    "genesis": r"G80|G90|GV80|G70|GV70|G60|GV60",
    "gmc": r"Yukon|Sierra|Terrain|Acadia|Savana|Canyon|Envoy|Jimmy",
    "great wall": r"Hover H[356]|Hover M[24]|Hover|Wingle|Voleex C30|Pao|Poer|Wingle",
    "haima": r"7",
    "haval": r"F7|F7x|H6|Dargo|H9|H2|H5|F5|F6|M6|Jolion",
    "hawtai": r"B11|Laville|B21|Santa Fe|Boliger|EV160|EV260|A25|A35",
    "hino": r"Dutro|Ranger|Profia|700 Series|300 Series|500 Series|Poncho",
    "honda": r"Civic|Accord|CR-V|Fit|Pilot|Odyssey|HR-V|Ridgeline|Passport|Jazz|Freed|Stepwgn|Shuttle|S2000|Legend|Integra|NSX|Insight|Clarity|Crosstour|Ascent|Brio|City|WR-V|BR-V|Vezel|CR-Z|Acty|Civic Type R|Accord Hybrid|Pilot Black Edition|Odyssey\sTouring|Stream|N-WGN",
    "hyundai": r"Solaris|Creta|Elantra|Tucson|Santa Fe|Sonata|Palisade|Kona|Veloster|i[123]0|Ioniq(?:Hybrid|Electric|5|6)|Nexo|Accent|Azera|Venue|Bayon|Staria|Porter|Grand Starex|Genesis G[7890]0",
    "infiniti": r"QX80|QX60|QX50|QX4|Q70|Q50|M|G35|FX|EX",
    "isuzu": r"F-Series|N-Series|NQR|NPR|Rodeo|Mu-X|Elf|D-Max",
    "jac": r"iEV6E|X200|T[68]|S[2345]|J5",
    "jaguar": r"F-Type|F-Pace|XF|X-Type|XJ|XE|S-Type|I-Pace|E-Pace",
    "jeep": r"Wrangler|Renegade|Patriot|Liberty|Gladiator|Grand Cherokee|Compass|Cherokee",
    "jetour": r"x(70|90) plus|dashing",
    "kia": r"Telluride|Sportage|Sorento|Seltos|Optima|Niro|Forte|Stinger|Stonic|Soul|Rio|Picanto|K[58]|EV[69]|Carnival|Carens|Ceed|Cerato",
    "koenigsegg": r"Jesko Absolut|Regera|One:1|Agera RS|Agera R|Agera|CCX|CC8S|Gemera",
    "lada": r"Priora|Largus|Kalina|Granta|Vesta|XRAY|Niva|4x4|Samara",
    "lamborghini": r"Aventador|Huracán|Urus|Sián|Countach LPI 800-4|Veneno|Centenario|Gallardo|Murciélago",
    "land rover": r"Range Rover Velar|Range Rover Sport|Discovery Sport|Range Rover|Freelander|Evoque|Discovery|Defender",
    "lexus": r"LX|LS|LC|IS|UX|RX|NX|LF-A|GX|ES",
    "lifan": r"Solano|Murman|Smily|X80|X70|X60|X50|720|Myway",
    "lincoln": r"Navigator|Nautilus|MKZ|MKX|MKC|Corsair|Aviator",
    "lotus": r"Emira|Evora|Exige|Elise|Esprit|7",
    "lucid": r"Air Dream Edition R|Air Dream Edition P|Air Grand Touring|Air Touring|Air Pure",
    "maserati": r"GranTurismo|GranCabrio|Quattroporte|MC20|Levante|Grecale|Ghibli",
    "maybach": r"S-Class|GLS-Class",
    "mazda": r"CX-90|CX-60|MX-30|CX-30|CX-9|CX-8|CX-7|CX-5|CX-4|CX-3|RX-8|RX-7|Mazda6|Mazda5|Mazda3|Mazda2|MX-5 Miata|Demio|BT-50",
    "mercedes-benz": r"Mercedes|A-(class|класс|klasse)?|B-(class|класс|klasse)?|C-(class|класс|klasse)?|E-(class|класс|klasse)?|G-(class|класс|klasse)?|M-(class|класс|klasse)?|S-(class|класс|klasse)?|V-(class|класс|klasse)?|GL-(class|класс|klasse)?|CLS(-class|-класс|-klasse)?|CLA(-class|-класс|-klasse)?|GLA(-class|-класс|-klasse)?|GLK(-class|-класс|-klasse)?|GLS(-class|-класс|-klasse)?|GLC(-class|-класс|-klasse)?|GLE(-class|-класс|-klasse)?|AMG GT|EQC|EQA|EQB|EQS|Sprinter|Vito|GLB SUV|EQE|AMG GT|EQV|AMG A|AMG C|AMG E|AMG GLC|AMG GLE",
    "mg": r"ZS EV|Hector Plus|Gloster|Hector|ZS|RX5|HS|GS|3|6|5|7|EV|Marvel R|MG4 Electric|MG5 Electric|MG6 PHEV|Extender|Mulan",
    "mini": r"Countryman|Clubman|Hardtop 4 Door|Hardtop 2 Door|Convertible|Cooper SE|John Cooper Works",
    "mitsubishi": r"Eclipse Cross|Pajero Sport|Outlander|Pajero|ASX",
    "nio": r"ES8|ES6|EC6|ET7|ET5|ES7",
    "nissan": r"Versa|Wingroad|Vanette|Urvan|Tsubame|Tino|Terrano|Teana|Stagea|Sunny|Silvia|Skyline|Serena|Safari|Rasheen|Quest|Pulsar|Primera|Presea|Presage|Otti|Nv100 Clipper|NP300|Note|Navara|Murano|Moco|Micra|March|Maxima|Lucino|Liberty|Latio|Lafesta|Juke|Interstar|Homy|Hypermini|GT-R|Fuga|Elgrand|Dualis|Dayz|Cube|Cima|Cedric|Caravan|Bluebird|Avenir|Atlas|Armada|Altima|Almera|Leaf|Livina|Evalia|Cefiro|AD|X-Trail|Titan|Tiida|Teana|Sylphy|Sentra|Rogue|Pickup|Patrol|NV350|NV200|NV100|Gloria|Clipper|Bassara|Pino|Roox|Otti|Kix|e-NV200|Ariya|400Z|Pathfinder|Qashqai|X-Terra|Tiida Latio|Fairlady Z|Bluebird Sylphy|370Z|350Z",
    "opel": r"Vivaro|Mokka|Insignia|Grandland|Crossland|Combo|Corsa|Astra",
    "pagani": r"Huayra Roadster BC|Huayra Roadster|Huayra BC|Huayra|Zonda HP Barchetta|Zonda Revolucion|Zonda Cinque|Zonda F|Zonda C12|Utopia",
    "polestar": r"Polestar 5|Polestar 4|Polestar 3|Polestar 2|Polestar 1",
    "pontiac": r"Solstice|Torrent|Montana SV6|Grand Prix|Vibe|GTO|Aztek|Sunfire|Bonneville|Trans Sport|Firebird|Trans Am",
    "porsche": r"918 Spyder|Panamera|Macan|Cayenne|Cayman|Boxster|Taycan|911",
    "ram": r"3500|2500|1500|ProMaster City|ProMaster|Dakota",
    "renault": r"Trafic SpaceClass|Megane E-Tech Electric|Kangoo Z.E.|Captur E-Tech Plug-in|Zoe E-Tech|Master Z.E.|Trafic|Scenic|Morphoz|Megane|Master|Latitude|Kadjar|Fluence|Espace|Captur|Arkana|Alaskan|Zoe|Twingo|Talisman|Koleos|Kangoo|Clio|Austral",
    "rivian": r"R1S|R1T",
    "rolls-royce": r"Phantom|Ghost|Wraith|Dawn|Cullinan|Spectre",
    "saab": r"9-7X|9-5|9-4X|9-3|9-2X|900",
    "saturn": r"Outlook|Sky|Relay|Ion|Vue|Aura|Astra",
    "scion": r"xD|xB|xA|tC|iQ|FR-S",
    "seat": r"Tarraco|Leon|Ibiza|Arona|Ateca|Alhambra",
    "skoda": r"Superb|Octavia|Kodiaq|Karoq|Rapid",
    "smart": r"forfour|fortwo|roadster",
    "ssangyong": r"Rexton|Musso|Korando|Tivoli|XLV",
    "subaru": r"WRX|XV|Outback|Legacy|Levorg|Impreza|Forester|Crosstrek|BRZ|Ascent",
    "suzuki": r"XL7|Vitara|Swift|SX4|S-Cross|Jimny|Ignis|Ertiga|Ciaz|Baleno|Alto|Wagon R|Dzire|Celerio|APV|Across|Swace",
    "tata": r"Safari|Nexon|Harrier|Altroz|Tiago|Tigor",
    "tesla": r"Model Y|Model X|Model S|Model 3|Roadster|Cybertruck",
    "toyota": r"Land Cruiser Prado|Corolla(?! Fielder|Rumion|Spacio|Verso)|Hilux Surf|Land Cruiser|Mark X Zio|Sprinter(?! Carib|Marino|Trueno)|Allex|Allion|Alphard|Altezza|Aqua|Aristo|Aurion|Auris|Avalon|Avensis|Aygo|bB|Belta|Blade|Brevis|C-HR|Caldina|Cami|Camry(?! Solara)|Carina(?!ED)|Celica|Chaser|Corolla(?:Axio|Ceres|Levin)|Corona(?:Exiv|Premio)|Cressida|Cresta|Crown|Curren|Cynos|Duet|Echo|Estima|FJ Cruiser|Fortuner|Funcargo|Gaia|Grand Hiace|Granvia|GT 86|Harrier|Hiace|Highlander|Hilux|Ipsum|Isis|Ist|Kluger|Lite Ace|Mark II|Mark X|Matrix|Mega Cruiser|Mirai|MR-S|MR2|Nadia|Noah|Opa|Origin|Paseo|Passo(?:Sette)?|Picnic|Platz|Porte|Premio|Previa|Prius|Probox|Progres|Pronard|Ractis|Raum|RAV4|Regius(?:Ace)?|Rush|Sai|Scepter|Sequoia|Sera|Sienna|Sienta|Soarer|Solara|Soluna|Spade|Sparky|Sprinter|Starlet|Succeed|Supra|Tacoma|Tercel|Tundra|Urban Cruiser|Vanguard|Vellfire|Venza|Verossa|Verso(?:-S)?|Vista(?:Ardeo)?|Vitz|Voltz|Voxy|Will|Windom|Wish|Zelas|4Runner|GT86|FJ Cruiser|Tank|Yaris",
    "volkswagen": r"Golf|Polo|Jetta|Passat|Tiguan|Touareg|Transporter|Arteon|Atlas|Taos|Amarok|Touran|Sharan|Caddy|Crafter|T-Roc|T-Cross|ID\.[34]|Beetle|Eos|Scirocco|Phaeton|Multivan|California|Caravelle|Tiguan Allspace|Teramont|Viloran|Tharu|Lamando|Virtus|Nivus|Saveiro|Gol|Polo Sedan|Jetta GLI|Atlas Cross Sport|ID\.[56]",
    "zeekr": r"001|x",
}


