transmission_regex = r'мкпп|механика|робот|вариатор|акпп|автомат'
odometer_regex = r'\d+ ?(?:\d{3} )?км'
fuel_regex = r'бензин|дизель|электро|гибрид|гбо'
horse_power_regex = r'(\d+)\s*л\.с\.'
engine_regex = r'\b\d+\.\d+\s*л?\b'

dict_param_separate = {
    'avito': '_',
    'drom': '_',
    'sberauto': '-'
}

dict_models = {
    '1 серии': r'1[- ]?(Series|серии|серия)',
    '2 серии': r'2[- ]?(Series|серии|серия)',
    '3 серии': r'3[- ]?(Series|серии|серия)',
    '4 серии': r'4[- ]?(Series|серии|серия)',
    '5 серии': r'5[- ]?(Series|серии|серия)',
    '6 серии': r'6[- ]?(Series|серии|серия)',
    '7 серии': r'7[- ]?(Series|серии|серия)',
    '8 серии': r'8[- ]?(Series|серии|серия)',
    'A-класс': r'A-(class|класс|klasse)?',
    'B-класс': r'B-(class|класс|klasse)?',
    'C-класс': r'C-(class|класс|klasse)?',
    'E-класс': r'E-(class|класс|klasse)?',
    'G-класс': r'G-(class|класс|klasse)?',
    'M-класс': r'M-(class|класс|klasse)?',
    'S-класс': r'S-(class|класс|klasse)?',
    'V-класс': r'V-(class|класс|klasse)?',
    'GL-класс': r'GL-(class|класс|klasse)?',
    'CLS-класс': r'CLS(-class|-класс|-klasse)?',
    'CLA-класс': r'CLA(-class|-класс|-klasse)?',
    'GLA-класс': r'GLA(-class|-класс|-klasse)?',
    'GLK-класс': r'GLK(-class|-класс|-klasse)?',
    'GLS-класс': r'GLS(-class|-класс|-klasse)?',
    'GLC-класс': r'GLC(-class|-класс|-klasse)?',
    'GLE-класс': r'GLE(-class|-класс|-klasse)?',
}


brand_models = {
    "toyota": r"Land Cruiser Prado|Corolla(?! Fielder|Rumion|Spacio|Verso)|Hilux Surf|Land Cruiser|Mark X Zio|Sprinter(?! Carib|Marino|Trueno)|Allex|Allion|Alphard|Altezza|Aqua|Aristo|Aurion|Auris|Avalon|Avensis|Aygo|bB|Belta|Blade|Brevis|C-HR|Caldina|Cami|Camry(?! Solara)|Carina(?!ED)|Celica|Chaser|Corolla(?:Axio|Ceres|Levin)|Corona(?:Exiv|Premio)|Cressida|Cresta|Crown|Curren|Cynos|Duet|Echo|Estima|FJ Cruiser|Fortuner|Funcargo|Gaia|Grand Hiace|Granvia|GT 86|Harrier|Hiace|Highlander|Hilux|Ipsum|Isis|Ist|Kluger|Lite Ace|Mark II|Mark X|Matrix|Mega Cruiser|Mirai|MR-S|MR2|Nadia|Noah|Opa|Origin|Paseo|Passo(?:Sette)?|Picnic|Platz|Porte|Premio|Previa|Prius|Probox|Progres|Pronard|Ractis|Raum|RAV4|Regius(?:Ace)?|Rush|Sai|Scepter|Sequoia|Sera|Sienna|Sienta|Soarer|Solara|Soluna|Spade|Sparky|Sprinter|Starlet|Succeed|Supra|Tacoma|Tercel|Tundra|Urban Cruiser|Vanguard|Vellfire|Venza|Verossa|Verso(?:-S)?|Vista(?:Ardeo)?|Vitz|Voltz|Voxy|Will|Windom|Wish|Zelas|4Runner|GT86|FJ Cruiser|Tank|Yaris",
    "honda": r"Civic|Accord|CR-V|Fit|Pilot|Odyssey|HR-V|Ridgeline|Passport|Jazz|Freed|Stepwgn|Shuttle|S2000|Legend|Integra|NSX|Insight|Clarity|Crosstour|Ascent|Brio|City|WR-V|BR-V|Vezel|CR-Z|Acty|Civic Type R|Accord Hybrid|Pilot Black Edition|Odyssey Touring|HR-V Sport|Stream|N-WGN",
    "volkswagen": r"Golf|Polo|Jetta|Passat|Tiguan|Touareg|Transporter|Arteon|Atlas|Taos|Amarok|Touran|Sharan|Caddy|Crafter|T-Roc|T-Cross|ID\.[34]|Beetle|Eos|Scirocco|Phaeton|Multivan|California|Caravelle|Tiguan Allspace|Teramont|Viloran|Tharu|Lamando|Virtus|Nivus|Saveiro|Gol|Polo Sedan|Jetta GLI|Atlas Cross Sport|ID\.[56]",
    "ford": r"Focus|Fiesta|Kuga|Mondeo|Explorer|F-150|Mustang|Escape|Expedition|Ranger|Bronco|Maverick|Fusion|Transit|Ecosport|Taurus|Edge|Flex|Expedition MAX|Super Duty|Raptor|Shelby GT500|Mustang Mach-E|F-150 Lightning|Bronco Sport|Ranger Raptor|Explorer ST|Expedition Platinum",
    "nissan": r"Pathfinder|Qashqai|X-Terra|Tiida Latio|Fairlady Z|NV350 Caravan|Bluebird Sylphy|NP300|NV100 Clipper|Altima|Armada|Atlas|Avenir|Bluebird|Caravan|Cefiro|Cima|Dualis|Elgrand|Evalia|Fuga|GT-R|Homy|Hypermini|Interstar|Lafesta|Latio|Liberty|Livina|Lucino|Maxima|Navara|NV200|Presage|Presea|Primera|Quest|Rogue|Safari|Serena|Stagea|Terrano|Tino|Tsubame|Urvan|Vanette|Wingroad|Almera|Juke|Leaf|March|Micra|Murano|Note|Patrol|Pickup|Sentra|Silvia|Skyline|Teana|Tiida|Titan|X-Trail|350Z|370Z|AD|Advan|Cube|Dayz|Moco|NP300|NV100 Clipper|Otti|Pulsar|Rasheen|Sunny|Versa",
    "bmw": r"2[- ]?(Series|серии|серия)|4[- ]?(Series|серии|серия)|8[- ]?(Series|серии|серия)|3[- ]?(Series|серии|серия)|5[- ]?(Series|серии|серия)|7[- ]?(Series|серии|серия)|X5|X3|Z4|X4|M4|M5|X6|X7|X1|1[- ]?(Series|серии)|6[- ]?(Series|серии|серия)|X2|X6|i3|i8|XM|X4 M|X5 M|X6 M|M2|M3|M8|iX|iX3|i4|i7|2 Series Gran Coupe|4 Series Gran Coupe|8 Series Gran Coupe|X3 M|X4 M Competition|M240i|M340i|M550i|Z4 M40i|X7 M60i|i4 M50|iX M60|X5 M Competition|X6 M Competition",
    "mercedes-benz": r"A-(class|класс|klasse)?|B-(class|класс|klasse)?|C-(class|класс|klasse)?|E-(class|класс|klasse)?|G-(class|класс|klasse)?|M-(class|класс|klasse)?|S-(class|класс|klasse)?|V-(class|класс|klasse)?|GL-(class|класс|klasse)?|CLS(-class|-класс|-klasse)?|CLA(-class|-класс|-klasse)?|GLA(-class|-класс|-klasse)?|GLK(-class|-класс|-klasse)?|GLS(-class|-класс|-klasse)?|GLC(-class|-класс|-klasse)?|GLE(-class|-класс|-klasse)?|AMG GT|EQC|EQA|EQB|EQS|Sprinter|Vito|GLB SUV|EQE|AMG GT|EQV|AMG A|AMG C|AMG E|AMG GLC|AMG GLE",
    "audi": r"A[3-8]|Q[3578]|TT|R8|RS[3456]|SQ[57]|e-tron",
    "hyundai": r"Solaris|Creta|Elantra|Tucson|Santa Fe|Sonata|Palisade|Kona|Veloster|i[123]0|Ioniq(?:Hybrid|Electric|5|6)|Nexo|Accent|Azera|Venue|Bayon|Staria|Porter|Grand Starex|Genesis G[7890]0",
    "kia": r"Ceed|Rio|Sportage|Cerato|Sorento|Optima|Stinger|Forte|Niro|Telluride|Carnival|Picanto|Stonic|Seltos|EV6|Soul|Carens|K[58]|EV9",
    "chevrolet": r"Aveo|Niva|Cruze|Malibu|Tahoe|Camaro|Silverado|Equinox|Traverse|Blazer|Trax|Bolt(?:EV|EUV)|Suburban|Colorado|Corvette|Spark|Onix|Tracker|Trailblazer|Captiva|Impala|Malibu Hybrid",
    "renault": r"Logan|Sandero|Duster|Kaptur|Koleos|Megane|Arkana|Trafic|Master|Clio|Captur|Kadjar|Zoe|Twingo|Fluence|Latitude|Talisman|Espace|Kangoo|Scenic|Alaskan|Austral|Morphoz|Megane E-Tech|Arkana E-Tech|Trafic SpaceClass|Kangoo Z\.E\.|Master Z\.E\.|Zoe E-Tech|Captur E-Tech Plug-in|Megane E-Tech Electric",
    "skoda": r"Octavia|Rapid|Superb|Kodiaq|Karoq",
    "mitsubishi": r"Outlander|ASX|Pajero(?:Sport)?|Eclipse Cross",
    "mazda": r"Mazda[23567]|CX-[3-9]0|CX-[3-9]|MX-5 Miata|BT-50|Demio|RX-[578]",
    "subaru": r"Outback|Forester|Impreza|XV|Legacy|Ascent|BRZ|WRX|Crosstrek|Levorg",
    "lexus": r"RX|ES|LX|NX|GX|IS|LS|LC|UX|LF-A",
    "suzuki": r"Vitara|Swift|SX4|Jimny|Ignis|Baleno|Ciaz|Ertiga|Kizashi",
    "lifan": r"X60|Solano|Myway|Murman|X50|X70|720|X80|Smily",
    "geely": r"Atlas|Coolray|Emgrand|Tugella|Azkarra|Borui|Geometry A|Preface|Vision X6|Monjaro",
    "acura": r"TLX|RDX|MDX|ILX|NSX|TL|TSX|ZDX|RLX",
    "alfa romeo": r"Giulia|Stelvio|4C|Giulietta|MiTo|Brera|Spider|159|Guilia Quadrifoglio",
    "bentley": r"Continental|Bentayga|Flying Spur|Mulsanne|Arnage|Azure|Brooklands|Turbo R",
    "brilliance": r"V5|H230|H330|H320|M2|V3|M1|H530|H220",
    "buick": r"Envision|Enclave|Encore|Regal|LaCrosse|Verano|Cascada|Excelle",
    "cadillac": r"Escalade|XT5|CT6|ATS|CTS|XT4|XT6|Eldorado|DeVille",
    "chery": r"Tiggo [2-9]|Arrizo|Bonus|Indis|Crosseastar|Exeed TXL",
    "citroen": r"C[1-8]|C-Elysée|Berlingo|Ami",
    "dacia": r"Duster|Sandero|Logan|Lodgy|Dokker|Spring|Jogger|Bigster",
    "daewoo": r"Nexia|Matiz|Gentra|Lacetti|Magnus|Lanos|Leganza|Nubira",
    "daihatsu": r"Terios|Sirion|Charade|Cuore|Mira|Rocky|Copen|Cast|Tanto",
    "dodge": r"Challenger|Charger|Durango|Journey|Dart|Ram|Viper|Grand Caravan",
    "dongfeng": r"S30|AX7|H30|Rich|580|Glory 580|Aeolus|Fengguang",
    "ds": r"DS 3|DS 4|DS 5|DS 7 Crossback|DS 9|DS 6",
    "fiat": r"Punto|500|Ducato|Doblo|Tipo|Panda|Cronos|Argo|Mobi",
    "gaz": r"Gazelle|Sobol|Valday|Sadko|Siber|GAZelle NEXT|GAZelle NN|Sobol NN|Siber NN",
    "genesis": r"G80|G90|GV80|G70|GV70|G60|GV60",
    "gmc": r"Yukon|Sierra|Terrain|Acadia|Savana|Canyon|Envoy|Jimmy",
    "great wall": r"Hover H[356]|Hover M[24]|Hover|Wingle|Voleex C30|Pao|Poer|Wingle",
    "haval": r"F7|F7x|H6|Dargo|H9|H2|H5|F5|F6|M6|Jolion",
    "hawtai": r"B11|Laville|B21|Santa Fe|Boliger|EV160|EV260|A25|A35",
    "hino": r"Dutro|Ranger|Profia|700 Series|300 Series|500 Series|Poncho",
    "infiniti": r"QX50|QX60|Q50|QX80|Q70|QX4|FX|G35|M|EX",
    "isuzu": r"D-Max|Mu-X|NQR|NPR|Elf|F-Series|N-Series|Rodeo",
    "jac": r"S2|S3|S5|T6|X200|J5|iEV6E|S4|T8",
    "jaguar": r"F-Pace|XF|E-Pace|XE|I-Pace|XJ|F-Type|X-Type|S-Type",
    "jeep": r"Wrangler|Cherokee|Compass|Gladiator|Renegade|Grand Cherokee|Patriot|Liberty",
    "lada": r"Granta|Vesta|XRAY|Largus|Niva|Priora|Kalina|4x4|Samara",
    "land rover": r"Range Rover|Discovery|Defender|Freelander|Evoque|Discovery Sport|Range Rover Sport|Range Rover Velar",
    "landwind": r"X5|X7|CS65|CV9|CC6|X2|X6|X8",
    "lincoln": r"Navigator|Aviator|Nautilus|Corsair|MKZ|MKX|MKC",
    "lotus": r"Elise|Exige|Evora|Emira|Esprit|7",
    "mahindra": r"Scorpio|Bolero|Thar|XUV500|KUV100|Marazzo",
    "maserati": r"Ghibli|Levante|Quattroporte|Grecale|MC20|GranTurismo|GranCabrio",
    "opel": r"Astra|Corsa|Mokka|Insignia|Crossland|Grandland|Vivaro|Combo",
    "peugeot": r"208|308|607|3008|5008|2008|Partner|Traveller|Rifter|Boxer",
    "porsche": r"911|Cayenne|Macan|Panamera|Taycan|Boxster|Cayman|918 Spyder",
    "zeekr": r"001|x",
    "haima": r"7",
    "gac": r"gs8",
    "jetour": r"x(70|90) plus|dashing",
    "datsun": r"mi-Do",
    "jaecoo": r"j7"
}


