@startuml
start
:Сбор информации о клиенте;
:Поиск свободного номера для клиента;
if (Есть подходящий номер?) then (да)
    :Сдача номера клиенту;
else (нет)
   :Проинформировать клиента об отсутствии подходящих номеров;
   stop
endif
:Фиксация даты поселения;
:Выезд клиента из гостиницы;
:Фиксация даты освобождения номера;
stop
@enduml