@startuml
left to right direction
:Работник отеля: as Receptionist

rectangle "Система отеля" {
    Receptionist --> (Получить финансовую статистику)
    Receptionist --> (Получить список номеров)
    Receptionist --> (Получить список клиентов)
    Receptionist --> (Заселить клиента в номер)

    (Получить финансовую статистику) --> (Предоставить клиентов в системе)
    (Получить финансовую статистику) --> (Предоставить поселения в системе)
    (Получить список номеров) --> (Предоставить номера в системе)
    (Получить список клиентов) --> (Предоставить клиентов в системе)
    (Заселить клиента в номер) --> (Проверить доступность номера)
}
@enduml