@startuml ActivityAfter
start
:Сбор информации от клиента;
:Поиск свободного номера для клиента;
if (Есть подходящий номер?) then (да)
  if (Сдача номера?) then (да)
    :Сдача номера клиенту;
    :Фиксация даты поселения;
  else (нет)
    :Бронирование номера;
    :Фиксация даты поселения;
    :Фиксация даты выселения;
  endif
    :Учет системы скидок;
else (нет)
   :Проинформировать клиента об отсутствии подходящих номеров; 
   stop
endif
:Выезд клиента из гостиницы;
if (Было заселение?) then (да)
  :Фиксация даты освобождения номера;
else(нет)
endif
stop
@enduml