@startuml PrecedentAfter
left to right direction
:Работник отеля: as Receptionist
:Клиент: as Client

rectangle "Система отеля" {
    Client --> (Получить список доступных номеров)
    Client --> (Забронировать номер)
    Receptionist --> (Забронировать номер)
    Receptionist --> (Авторизоваться в системе)
    Receptionist --> (Получить финансовую статистику)
    Receptionist --> (Получить список доступных номеров)
    Receptionist --> (Получить список клиентов)
    Receptionist --> (Получить список бронирований)
    Receptionist --> (Получить список заселений)
    Receptionist --> (Заселить клиента в номер)
    Receptionist --> (Добавить клиента)

    
    (Получить список заселений) --> (Предоставить заселения в системе)
    (Получить список бронирований) --> (Предоставить бронирования в системе)
    (Получить финансовую статистику) --> (Предоставить клиентов в системе)
    (Получить финансовую статистику) --> (Предоставить заселения в системе)
    (Получить финансовую статистику) --> (Предоставить бронирования в системе)
    (Получить список доступных номеров) --> (Предоставить номера в системе)
    (Получить список доступных номеров) --> (Получить информацию о номере)
    (Получить список клиентов) --> (Предоставить клиентов в системе)
    (Заселить клиента в номер) --> (Проверить доступность номера)
    (Забронировать номер) --> (Проверить доступность номера)
}
@enduml